#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod access_control;
pub mod context;
pub mod erc165;
pub mod erc20;
pub mod i_access_control;
pub mod ierc165;
pub mod ierc20;
pub mod ierc20_metadata;
pub mod inbox;
pub mod kyc_wallet;
pub mod math;
pub mod my_token;
pub mod outbox;
pub mod signed_math;
pub mod strings;
pub mod token_bridge;
